spring.application.name=lume-loginbackend

spring.datasource.url=jdbc:postgresql://ep-cold-band-b1m9h4we-pooler.c-5.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&ssl=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Am95dLjOwnDT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect